name: CI/CD to EKS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1   
  ECR_REPOSITORY: hello-k8s        
  CLUSTER_NAME: hello-eks        
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------- AUTH --------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # -------------------- BUILD & PUSH --------------------
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:cache
          cache-to: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:cache,mode=max

        env:
          DOCKER_BUILDKIT: 1

      # -------------------- DEPLOY --------------------
      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to EKS
        run: |
          # Update image in deployment manifest
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          echo "Deploying image: $IMAGE_URI"
          sed -i "s|image:.*|image: $IMAGE_URI|g" k8s_manifests/deployment.yaml
          kubectl apply -f k8s_manifests/deployment.yaml
          kubectl rollout status deployment/hello-deployment --timeout=120s